server {
    listen 80;
    root /usr/share/nginx/html;
    add_header Access-Control-Allow-Origin *;

    location = /renis-verify.iife.js {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
